version: '3.9'

services:
  splash:
    image: scrapinghub/splash:3.5
    container_name: my_splash
    networks:
      - net
    ports:
      - 8050:8050

  scrapy:
    depends_on:
      - splash
    build:
      context: ..
      dockerfile: Dockerfile.splash
    image: scrapy:2.6.1
    container_name: my_scrapy
    networks:
      - net
    env_file:
      - ../src/.env
    volumes:
      - ../src:/usr/src
    tty: true

networks:
  net: