version: "3"

services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
        - ../src:/usr/src
    environment:
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      TZ: "Asia/Tokyo"
    tty: true