version: "3"

services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      AUTO_RACE_USER_NUMBER: ${AUTO_RACE_USER_NUMBER}
      AUTO_RACE_PASSWORD: ${AUTO_RACE_PASSWORD}
      AUTO_RACE_PIN: ${AUTO_RACE_PIN}
      POINT_INCOME_EMAIL: ${POINT_INCOME_EMAIL}
      POINT_INCOME_PASSWORD: ${POINT_INCOME_PASSWORD}
      SPAT4_MEMBERNUM: ${SPAT4_MEMBERNUM}
      SPAT4_MEMBERID: ${SPAT4_MEMBERID}
      SPAT4_MEMBERPASS: ${SPAT4_MEMBERPASS}
    volumes:
      - ../src:/usr/src
    tty: true