version: '3'
services:
  selenium:
    container_name: selenium-chrome
    # image: selenium/standalone-chrome-debug:3.141.59-20210929
    # image: seleniarm/standalone-chromium:latest
    image: seleniarm/standalone-chromium:4.1.4-20220429
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: "2gb"
  app:
    depends_on:
      - selenium
    container_name: app
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
        - ../app:/usr/src/app
    tty: true