import os

# スラック
SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL")

# オートレース
AUTO_RACE_USER_NUMBER = os.getenv("AUTO_RACE_USER_NUMBER")
AUTO_RACE_PASSWORD = os.getenv("AUTO_RACE_PASSWORD")
AUTO_RACE_PIN = os.getenv("AUTO_RACE_PIN")

# ポイントインカム
POINT_INCOME_EMAIL = os.getenv("POINT_INCOME_EMAIL")
POINT_INCOME_PASSWORD = os.getenv("POINT_INCOME_PASSWORD")

# SPAT4
SPAT4_MEMBERNUM = os.getenv("SPAT4_MEMBERNUM")
SPAT4_MEMBERID = os.getenv("SPAT4_MEMBERID")
SPAT4_MEMBERPASS = os.getenv("SPAT4_MEMBERPASS")
